[project]
name = "pydecoys"
version = "0.2.1"
description = "Proteomics decoy utilities for Python"
license = "GPL-3.0-or-later"
authors = [
    { name = "Bruno Maestri A Becker", email = "bruno.maestri@edu.pucrs.br" }
]
readme = "README.md"
requires-python = ">=3.12"
keywords = [
    'python',
    'bioinformatics',
    'protein',
    'proteomics',
    'proteogenomics',
    'bionformatics-tool'
]
classifiers = [
    'Development Status :: 4 - Beta',
    'Environment :: Console',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules'
]


[project.urls]
hompegage = "https://github.com/CPBMF/pydecoys"
repository = "https://github.com/CPBMF/pydecoys"
changelog = "https://github.com/CPBMF/pydecoys/blob/main/CHANGELOG.md"
documentation = "https://cpbmf.github.io/pydecoys/"
tracker = "https://github.com/CPBMF/pydecoys/issues"


[project.scripts]
pydecoys = "pydecoys.__main__:main"


[tool.poetry.group.biopython.dependencies]
biopython = "^1.87"


[tool.poetry.group.dev]
optional = true


[tool.poetry.group.dev.dependencies]
mypy = "^2.1.0"
flake8 = "^7.3.0"
pytest = "^9.0.3"
pytest-cov = "^7.1.0"
pytest-missing-modules = "^0.2.2"


[tool.poetry.group.docs]
optional = true


[tool.poetry.group.docs.dependencies]
sphinx = "^9.1.0"
sphinx-rtd-theme = "^3.1.0"
doc8 = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.esbonio.sphinx]
buildCommand = ["sphinx-build", "-M", "dirhtml", ".", "./_build"]
pythonCommand = ["${venv:.venv}"]


[tool.doc8]
ignore = ["D004"]
ignore-path = ["docs/build/*"]
max-line-length = 79


[tool.coverage.run]
omit = ["pydecoys/_bio.py"]
